(source gnu)
(source melpa)

(depends-on "ac-html")
(depends-on "ac-html-bootstrap")
(depends-on "ac-js2")
(depends-on "coffee-mode")
(depends-on "emmet-mode")
(depends-on "expand-region")
(depends-on "git-gutter")
(depends-on "gruvbox-theme")
(depends-on "helm")
(depends-on "helm-dash")
(depends-on "helm-projectile")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "js2-mode")
(depends-on "less-css-mode")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "multiple-cursors")
(depends-on "nodejs-repl")
(depends-on "projectile")
(depends-on "spacegray-theme")
(depends-on "web-beautify")
(depends-on "web-mode")
(depends-on "yaml-mode")

